services:
  phalanx_db:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - phalanx-db-storage:/app/p2p-db-storage
      - phalanx-db-data:/app/db_data
    environment:
      - NODE_ENV=production
      - DEBUG=true

volumes:
  phalanx-db-storage:
  phalanx-db-data:
